import { StyleSheet } from "react-native";

export const authStyles = StyleSheet.create({
  centered: {
    flex: 1,
    backgroundColor: "#0d0e0f",
    alignItems: "center",
    justifyContent: "center",
  },
  container: {
    flex: 1,
    backgroundColor: "#0d0e0f",
    padding: 24,
    justifyContent: "center",
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: "#fff",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: "#9ca3af",
    marginBottom: 24,
  },
  label: {
    fontSize: 12,
    fontWeight: "600",
    color: "#9ca3af",
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  input: {
    borderWidth: 1,
    borderColor: "#2d2f31",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    marginBottom: 16,
    color: "#fff",
    backgroundColor: "#121314",
  },
  primaryButton: {
    backgroundColor: "#945cb4",
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 8,
  },
  primaryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  linkButton: {
    marginTop: 20,
    alignItems: "center",
  },
  linkText: {
    fontSize: 14,
    color: "#9ca3af",
  },
  linkTextBold: {
    color: "#e6b4ff",
    fontWeight: "600",
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  error: {
    marginTop: 16,
    fontSize: 14,
    color: "#fca5a5",
  },
});

export const appStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#0d0e0f",
  },
  container: {
    flex: 1,
    backgroundColor: "#0d0e0f",
    padding: 24,
    justifyContent: "center",
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: "#fff",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: "#9ca3af",
    marginBottom: 24,
  },
  tabLoader: {
    marginVertical: 32,
  },
  tabCard: {
    borderWidth: 1,
    borderColor: "#2d2f31",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    backgroundColor: "#1b1c1d",
  },
  tabTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#fff",
    marginBottom: 8,
  },
  tabUrl: {
    fontSize: 14,
    color: "#e6b4ff",
    marginBottom: 8,
  },
  tabUpdated: {
    fontSize: 12,
    color: "#9ca3af",
  },
  signedInAs: {
    fontSize: 13,
    color: "#9ca3af",
    marginTop: 16,
    marginBottom: 8,
    textAlign: "center",
  },
  hint: {
    fontSize: 14,
    color: "#9ca3af",
    lineHeight: 20,
  },
  error: {
    marginTop: 16,
    fontSize: 14,
    color: "#fca5a5",
  },
  primaryButton: {
    backgroundColor: "#945cb4",
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 8,
  },
  primaryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  secondaryButton: {
    backgroundColor: "#1b1c1d",
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 24,
    borderWidth: 1,
    borderColor: "#2d2f31",
  },
  secondaryButtonText: {
    color: "#f3e8ff",
    fontSize: 16,
    fontWeight: "600",
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  screen: {
    flex: 1,
    backgroundColor: "#0d0e0f",
    padding: 24,
  },
  createContent: {
    paddingBottom: 32,
  },
  screenHeader: {
    marginBottom: 24,
  },
  groupFocusTimer: {
    borderWidth: 1,
    borderColor: "#2d2f31",
    borderRadius: 12,
    padding: 20,
    marginBottom: 24,
    backgroundColor: "#1b1c1d",
    alignItems: "center",
  },
  groupFocusTimerValue: {
    fontSize: 36,
    fontWeight: "700",
    color: "#fff",
    marginBottom: 4,
  },
  groupFocusTimerLabel: {
    fontSize: 13,
    color: "#a3a3a3",
    textAlign: "center",
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: 24,
    gap: 12,
  },
  detailLogList: {
    flex: 1,
  },
  detailLogContent: {
    paddingBottom: 24,
    gap: 12,
  },
  detailLogCard: {
    borderWidth: 1,
    borderColor: "#2d2f31",
    borderRadius: 12,
    padding: 16,
    backgroundColor: "#1b1c1d",
  },
  detailLogHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  detailLogName: {
    flex: 1,
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
  },
  detailLogTotal: {
    fontSize: 16,
    fontWeight: "700",
    color: "#e6b4ff",
  },
  detailLogMeta: {
    fontSize: 12,
    color: "#9ca3af",
    marginBottom: 12,
  },
  detailLogEmpty: {
    fontSize: 13,
    color: "#9ca3af",
  },
  detailDomainRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: "#2d2f31",
  },
  detailDomainRank: {
    width: 24,
    fontSize: 12,
    fontWeight: "700",
    color: "#9ca3af",
  },
  detailDomainName: {
    flex: 1,
    fontSize: 14,
    color: "#fff",
  },
  detailDomainTime: {
    fontSize: 13,
    fontWeight: "600",
    color: "#9ca3af",
  },
  tetherCard: {
    borderWidth: 1,
    borderColor: "#2d2f31",
    borderRadius: 12,
    padding: 16,
    backgroundColor: "#1b1c1d",
  },
  tetherCardTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#fff",
    marginBottom: 4,
  },
  tetherCardMeta: {
    fontSize: 13,
    color: "#9ca3af",
  },
  memberCard: {
    borderWidth: 1,
    borderColor: "#2d2f31",
    borderRadius: 12,
    padding: 16,
    backgroundColor: "#1b1c1d",
  },
  memberHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  statusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 8,
  },
  statusWorking: {
    backgroundColor: "#16a34a",
  },
  statusIdle: {
    backgroundColor: "#ca8a04",
  },
  statusOffline: {
    backgroundColor: "#9ca3af",
  },
  memberName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
    flex: 1,
  },
  memberStatus: {
    fontSize: 12,
    color: "#9ca3af",
    textTransform: "uppercase",
    fontWeight: "600",
  },
  memberTabTitle: {
    fontSize: 15,
    color: "#e5e7eb",
    marginBottom: 4,
  },
  memberMeta: {
    fontSize: 12,
    color: "#9ca3af",
  },
  inviteCode: {
    fontSize: 24,
    fontWeight: "700",
    letterSpacing: 2,
    color: "#e6b4ff",
    marginVertical: 8,
  },
  rowActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
  },
  flexButton: {
    flex: 1,
  },
  topBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  linkText: {
    fontSize: 14,
    color: "#e6b4ff",
    fontWeight: "600",
  },
  emptyState: {
    fontSize: 14,
    color: "#9ca3af",
    marginTop: 8,
    lineHeight: 20,
  },
  tetherTabBar: {
    flexDirection: "row",
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: "#2d2f31",
    paddingTop: 12,
    marginTop: 12,
  },
  tetherTabButton: {
    flex: 1,
    alignItems: "center",
    borderRadius: 12,
    paddingVertical: 10,
    backgroundColor: "#1b1c1d",
    borderWidth: 1,
    borderColor: "#2d2f31",
  },
  tetherTabButtonActive: {
    backgroundColor: "#945cb4",
    borderColor: "#e6b4ff",
  },
  tetherTabIcon: {
    fontSize: 16,
    fontWeight: "700",
    color: "#9ca3af",
    marginBottom: 2,
  },
  tetherTabLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#9ca3af",
  },
  tetherTabTextActive: {
    color: "#fff",
  },
  allowlistPanel: {
    flex: 1,
  },
  allowlistTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fff",
    marginBottom: 8,
  },
  allowlistDescription: {
    fontSize: 14,
    color: "#9ca3af",
    marginBottom: 16,
    lineHeight: 20,
  },
  allowlistList: {
    flex: 1,
  },
  allowlistListContent: {
    paddingBottom: 16,
    gap: 10,
  },
  allowlistCurrentSection: {
    marginBottom: 16,
  },
  allowlistCurrentList: {
    gap: 10,
  },
  allowlistSectionTitle: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
    marginBottom: 8,
  },
  allowlistRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#2d2f31",
    borderRadius: 12,
    padding: 14,
    backgroundColor: "#1b1c1d",
  },
  allowlistRowText: {
    flex: 1,
  },
  allowlistTypeBadge: {
    fontSize: 11,
    fontWeight: "700",
    color: "#9ca3af",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  allowlistValue: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
  },
  allowlistRemoveButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  allowlistRemoveText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#fca5a5",
  },
  allowlistForm: {
    borderTopWidth: 1,
    borderTopColor: "#2d2f31",
    paddingTop: 16,
    marginTop: 8,
  },
  allowlistFormLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#9ca3af",
    marginBottom: 10,
  },
  allowlistTypeRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  allowlistTypeButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#2d2f31",
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: "center",
    backgroundColor: "#121314",
  },
  allowlistTypeButtonActive: {
    backgroundColor: "#945cb4",
    borderColor: "#e6b4ff",
  },
  allowlistTypeButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#fff",
  },
  allowlistTypeButtonTextActive: {
    color: "#fff",
  },
  allowlistInput: {
    borderWidth: 1,
    borderColor: "#2d2f31",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    marginBottom: 12,
    color: "#fff",
    backgroundColor: "#121314",
  },
  detectedAppsHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 12,
  },
  detectedAppsHeaderText: {
    flex: 1,
  },
  detectedAppsRefreshButton: {
    borderRadius: 8,
    backgroundColor: "#1b1c1d",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  detectedAppsRefreshText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "700",
  },
  detectedAppsList: {
    borderTopWidth: 1,
    borderTopColor: "#2d2f31",
    marginBottom: 12,
  },
  selectedAppsPanel: {
    borderWidth: 1,
    borderColor: "#2d2f31",
    borderRadius: 12,
    backgroundColor: "#1b1c1d",
    padding: 14,
    marginBottom: 12,
  },
  selectedAppsTitle: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 8,
  },
  selectedAppRow: {
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#2d2f31",
    paddingTop: 10,
    marginTop: 10,
  },
  selectedAppRemoveButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  selectedAppRemoveText: {
    color: "#fca5a5",
    fontSize: 13,
    fontWeight: "700",
  },
  detectedAppsSearchInput: {
    borderWidth: 1,
    borderColor: "#2d2f31",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    marginBottom: 12,
    color: "#fff",
    backgroundColor: "#121314",
  },
  detectedAppRow: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#2d2f31",
    paddingVertical: 12,
  },
  detectedAppRowSelected: {
    backgroundColor: "#231a28",
  },
  detectedAppRowText: {
    flex: 1,
    paddingRight: 12,
  },
  detectedAppIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    marginRight: 12,
  },
  detectedAppIconFallback: {
    width: 36,
    height: 36,
    borderRadius: 8,
    marginRight: 12,
    backgroundColor: "#2d2f31",
    alignItems: "center",
    justifyContent: "center",
  },
  detectedAppIconFallbackText: {
    color: "#e6b4ff",
    fontSize: 15,
    fontWeight: "700",
  },
  detectedAppName: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 3,
  },
  detectedAppMeta: {
    color: "#9ca3af",
    fontSize: 12,
  },
  detectedAppCheck: {
    color: "#9ca3af",
    fontSize: 13,
    fontWeight: "700",
  },
  detectedAppCheckSelected: {
    color: "#16a34a",
  },
  appShell: {
    flex: 1,
    backgroundColor: "#0d0e0f",
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  brandMark: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#1b1c1d",
    borderWidth: 1,
    borderColor: "#4d2d5d",
    alignItems: "center",
    justifyContent: "center",
  },
  brandMarkText: {
    color: "#e6b4ff",
    fontSize: 18,
    fontWeight: "900",
  },
  headerIconButton: {
    borderWidth: 1,
    borderColor: "#2d2f31",
    backgroundColor: "#1b1c1d",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  headerIconText: {
    color: "#e6b4ff",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  sectionLabel: {
    color: "#6b7280",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 10,
  },
  actionStack: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  actionCard: {
    borderWidth: 1,
    borderColor: "#2d2f31",
    backgroundColor: "#1b1c1d",
    borderRadius: 14,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
  },
  actionCardCompact: {
    flex: 1,
    minHeight: 132,
    flexDirection: "column",
    alignItems: "flex-start",
  },
  actionIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "#281735",
    borderWidth: 1,
    borderColor: "#4d2d5d",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  actionIconCompact: {
    width: 42,
    height: 42,
    marginRight: 0,
    marginBottom: 12,
  },
  actionIconSecondary: {
    backgroundColor: "#2b2030",
    borderColor: "#5f435f",
  },
  actionIconText: {
    color: "#e6b4ff",
    fontSize: 24,
    fontWeight: "800",
  },
  actionBody: {
    flex: 1,
  },
  actionTitle: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 3,
  },
  actionSubtitle: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "600",
  },
  cardChevron: {
    color: "#6b7280",
    fontSize: 24,
    fontWeight: "300",
  },
  searchRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#2d2f31",
    backgroundColor: "#1b1c1d",
    color: "#fff",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 14,
  },
  filterButton: {
    width: 46,
    borderWidth: 1,
    borderColor: "#2d2f31",
    backgroundColor: "#1b1c1d",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  filterButtonActive: {
    backgroundColor: "#e6b4ff",
    borderColor: "#e6b4ff",
  },
  filterButtonText: {
    color: "#9ca3af",
    fontWeight: "900",
  },
  filterButtonTextActive: {
    color: "#2b112f",
  },
  filterPanel: {
    borderWidth: 1,
    borderColor: "#2d2f31",
    backgroundColor: "#1b1c1d",
    borderRadius: 12,
    padding: 12,
    marginBottom: 18,
  },
  sortRow: {
    flexDirection: "row",
    gap: 8,
  },
  sortChip: {
    flex: 1,
    backgroundColor: "#121314",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2d2f31",
    paddingVertical: 8,
    alignItems: "center",
  },
  sortChipActive: {
    backgroundColor: "#e2bae1",
    borderColor: "#e2bae1",
  },
  sortChipText: {
    color: "#9ca3af",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "capitalize",
  },
  sortChipTextActive: {
    color: "#2b112f",
  },
  tetherCardRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  tetherAvatar: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "#252627",
    borderWidth: 1,
    borderColor: "#3f3f46",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  tetherAvatarText: {
    color: "#e6b4ff",
    fontSize: 18,
    fontWeight: "900",
  },
  tetherCardBody: {
    flex: 1,
  },
  tetherCardFooter: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  badge: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#2d2f31",
    backgroundColor: "#121314",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  badgeText: {
    color: "#9ca3af",
    fontSize: 11,
    fontWeight: "800",
  },
  badgeActive: {
    borderColor: "#064e3b",
    backgroundColor: "#052e26",
  },
  badgeActiveText: {
    color: "#34d399",
  },
  metricGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  metricCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#2d2f31",
    backgroundColor: "#1b1c1d",
    borderRadius: 14,
    padding: 14,
  },
  metricLabel: {
    color: "#6b7280",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  metricValue: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "900",
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "#121314",
    borderWidth: 1,
    borderColor: "#2d2f31",
    overflow: "hidden",
    marginTop: 12,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#945cb4",
  },
  profileHero: {
    alignItems: "center",
    marginTop: 12,
    marginBottom: 24,
  },
  profileAvatar: {
    width: 112,
    height: 112,
    borderRadius: 28,
    backgroundColor: "#1b1c1d",
    borderWidth: 1,
    borderColor: "#4d2d5d",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  profileAvatarText: {
    color: "#e6b4ff",
    fontSize: 42,
    fontWeight: "900",
  },
  profileBadge: {
    backgroundColor: "#945cb4",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 5,
    marginBottom: 14,
  },
  profileBadgeText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  profileName: {
    color: "#fff",
    fontSize: 30,
    fontWeight: "900",
    marginBottom: 8,
  },
  profileBio: {
    color: "#9ca3af",
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
  },
});
